Repository 9oormthon2024-T5-SoriSoop/soridam-server, pull requests merged in 2024-12, with the labels that each got.

#4 feature/#3 ci workflow 파일 작성
  .github/workflows/pull-request-build-check.yml
Labels: feature

#7 refactor/#6 db 컬럼 세부 설정
  build.gradle
  src/main/java/com/sorisoop/server/common/util/GeometryUtils.java
  src/main/java/com/sorisoop/server/config/JpaConfig.java
  src/main/java/com/sorisoop/server/noise/domain/Noise.java
  src/main/java/com/sorisoop/server/noise/dto/NoiseResponse.java
  src/main/java/com/sorisoop/server/review/domain/Review.java
  src/main/resources/application.yml
Labels: refactor

#15 hotfix/#14 hotfix entity generatedvalue 설정
  src/main/java/com/soridam/server/common/domain/User.java
  src/main/java/com/soridam/server/noise/domain/Noise.java
Labels: hotfix

#21 Feature/#10 setting user data
  src/main/java/com/soridam/server/noise/domain/Noise.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: feature

#23 refactor/#22 user 패키지 분리
  src/main/java/com/soridam/server/noise/controller/NoiseApiController.java
  src/main/java/com/soridam/server/noise/domain/Noise.java
  src/main/java/com/soridam/server/review/domain/Review.java
  src/main/java/com/soridam/server/review/exception/ReviewExceptionCode.java
  src/main/java/com/soridam/server/review/exception/ReviewNotFoundException.java
  src/main/java/com/soridam/server/review/repository/JpaReviewRepository.java
  src/main/java/com/soridam/server/review/service/ReviewService.java
  src/main/java/com/soridam/server/user/controller/UserApiController.java
  src/main/java/com/soridam/server/user/domain/User.java
  src/main/java/com/soridam/server/user/repository/JpaUserRepository.java
  src/main/java/com/soridam/server/user/service/UserService.java
Labels: refactor

#24 feature/#16 유저 마이페이지 조회
  src/main/java/com/soridam/server/noise/controller/NoiseApiController.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseSummaryListResponse.java
  src/main/java/com/soridam/server/noise/repository/JpaNoiseRepository.java
  src/main/java/com/soridam/server/noise/service/NoiseService.java
  src/main/java/com/soridam/server/user/controller/UserApiController.java
  src/main/java/com/soridam/server/user/domain/User.java
  src/main/java/com/soridam/server/user/exception/UserExceptionCode.java
  src/main/java/com/soridam/server/user/exception/UserNotFoundException.java
  src/main/java/com/soridam/server/user/service/UserService.java
Labels: feature

#25 Feature/#11 add api decibel
  src/main/java/com/soridam/server/noise/controller/NoiseApiController.java
  src/main/java/com/soridam/server/noise/dto/request/NoiseCreateRequest.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseCreateResponse.java
  src/main/java/com/soridam/server/noise/service/NoiseService.java
  src/main/java/com/soridam/server/user/controller/UserApiController.java
  src/main/java/com/soridam/server/user/domain/User.java
  src/main/java/com/soridam/server/user/repository/JpaUserRepository.java
Labels: feature

#27 feature/#12 noise 주변 검색
  src/main/java/com/soridam/server/noise/controller/NoiseApiController.java
  src/main/java/com/soridam/server/noise/dto/enums/NoiseLevel.java
  src/main/java/com/soridam/server/noise/dto/enums/Radius.java
  src/main/java/com/soridam/server/noise/dto/request/NoiseCreateRequest.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseResponse.java
  src/main/java/com/soridam/server/noise/repository/QueryNoiseRepository.java
  src/main/java/com/soridam/server/noise/service/NoiseService.java
  src/main/java/com/soridam/server/user/service/UserService.java
Labels: feature

#28 Noise 데이터 delete 삭제 API 구현
  src/main/java/com/soridam/server/noise/controller/NoiseApiController.java
  src/main/java/com/soridam/server/noise/service/NoiseService.java
Labels: feature

#29 feature/#13 해당 좌표 소음 상세 조회 구현
  src/main/java/com/soridam/server/noise/controller/NoiseApiController.java
  src/main/java/com/soridam/server/noise/repository/QueryNoiseRepository.java
  src/main/java/com/soridam/server/noise/service/NoiseService.java
Labels: feature

#31 refactor/#30 코드 리팩토링
  build.gradle
  src/main/java/com/soridam/server/config/GeometryConfig.java
  src/main/java/com/soridam/server/config/SwaggerConfig.java
  src/main/java/com/soridam/server/config/WebConfig.java
  src/main/java/com/soridam/server/noise/controller/NoiseApiController.java
  src/main/java/com/soridam/server/noise/dto/request/NoiseCreateRequest.java
  src/main/java/com/soridam/server/noise/dto/request/NoiseSearchRequest.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseCreateResponse.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseDetailResponse.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseListResponse.java
  src/main/java/com/soridam/server/noise/dto/response/NoisePersistResponse.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseResponse.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseReviewResponse.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseSearchResponse.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseSummaryListResponse.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseSummaryResponse.java
  src/main/java/com/soridam/server/noise/dto/response/NoiseTimeAvgResponse.java
  src/main/java/com/soridam/server/noise/repository/JpaNoiseRepository.java
  src/main/java/com/soridam/server/noise/repository/QueryNoiseRepository.java
  src/main/java/com/soridam/server/noise/service/NoiseService.java
  src/main/java/com/soridam/server/user/controller/UserApiController.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: refactor

#35 feat/#34 유저 로그인, 회원가입 구현
  settings.gradle
  soridam-api/build.gradle
  soridam-api/src/main/java/sorisoop/soridam/api/auth/application/AuthService.java
  soridam-api/src/main/java/sorisoop/soridam/api/auth/presentation/AuthApiController.java
  soridam-api/src/main/java/sorisoop/soridam/api/auth/presentation/request/jwt/JwtLoginRequest.java
  soridam-api/src/main/java/sorisoop/soridam/api/auth/presentation/response/jwt/JwtResponse.java
  soridam-api/src/main/java/sorisoop/soridam/api/noise/application/NoiseService.java
  soridam-api/src/main/java/sorisoop/soridam/api/noise/presentation/NoiseApiController.java
  soridam-api/src/main/java/sorisoop/soridam/api/noise/presentation/exception/NoiseNotFoundException.java
  soridam-api/src/main/java/sorisoop/soridam/api/noise/presentation/response/NoisePersistResponse.java
  soridam-api/src/main/java/sorisoop/soridam/api/noise/presentation/response/NoiseSummaryResponse.java
  soridam-api/src/main/java/sorisoop/soridam/api/user/application/UserService.java
  soridam-api/src/main/java/sorisoop/soridam/api/user/presentation/UserApiController.java
  soridam-api/src/main/java/sorisoop/soridam/api/user/presentation/request/UserCreateRequest.java
  soridam-api/src/main/java/sorisoop/soridam/api/user/presentation/response/UserPersistResponse.java
  soridam-api/src/main/resources/application.yml
  soridam-api/src/main/resources/data.sql
  soridam-auth/build.gradle
  soridam-auth/src/main/java/sorisoop/soridam/auth/config/SecurityConfig.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/jwt/JwtAuthenticationFilter.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/jwt/JwtProperties.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/jwt/JwtProvider.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/jwt/exception/JwtExceptionCode.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/jwt/exception/JwtExpiredException.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/jwt/exception/JwtInvalidException.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/jwt/exception/JwtMalformedException.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/jwt/exception/JwtSignatureInvalidException.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/jwt/exception/JwtUnsupportedException.java
  soridam-common/src/main/java/sorisoop/soridam/common/config/WebConfig.java
  soridam-domain/src/main/java/sorisoop/soridam/domain/noise/domain/Noise.java
  soridam-domain/src/main/java/sorisoop/soridam/domain/noise/infrastructure/JpaNoiseRepository.java
  soridam-domain/src/main/java/sorisoop/soridam/domain/user/domain/User.java
  soridam-domain/src/main/java/sorisoop/soridam/domain/user/exception/InvalidPasswordException.java
  soridam-domain/src/main/java/sorisoop/soridam/domain/user/exception/UserDomainExceptionCode.java
  soridam-domain/src/main/java/sorisoop/soridam/domain/user/infrastructure/JpaUserRepository.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/EnableSoriDamConfig.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/uuid/PrefixedUuid.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/uuid/PrefixedUuidGenerator.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/uuid/UuidPrefix.java
Labels: feature

#37 refactor/#36 entity id 설정 수정
  .github/PULL_REQUEST_TEMPLATE.md
  soridam-api/src/main/java/sorisoop/soridam/api/config/InfraConfig.java
  soridam-api/src/main/java/sorisoop/soridam/api/noise/application/NoiseService.java
  soridam-api/src/main/java/sorisoop/soridam/api/user/application/UserService.java
  soridam-auth/build.gradle
  soridam-common/src/main/java/sorisoop/soridam/common/domain/BaseTimeEntity.java
  soridam-common/src/main/java/sorisoop/soridam/common/domain/UuidExtractable.java
  soridam-common/src/main/java/sorisoop/soridam/common/util/GeometryUtils.java
  soridam-common/src/main/java/sorisoop/soridam/common/uuid/PrefixedUuid.java
  soridam-common/src/main/java/sorisoop/soridam/common/uuid/PrefixedUuidGenerator.java
  soridam-common/src/main/java/sorisoop/soridam/common/uuid/UuidPrefix.java
  soridam-domain/src/main/java/sorisoop/soridam/domain/noise/domain/Noise.java
  soridam-domain/src/main/java/sorisoop/soridam/domain/user/domain/User.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/SoriDamConfig.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/GeometryConfig.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/PropertiesConfig.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/base/EnableSoriDamConfig.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/base/SoriDamConfig.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/base/SoriDamConfigGroup.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/base/SoriDamConfigImportSelector.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/jpa/JpaAuditingConfig.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/jpa/JpaConfig.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/properties/PropertiesConfig.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/swagger/SwaggerConfig.java
  soridam-infra/src/main/java/sorisoop/soridam/infra/config/web/WebConfig.java
Labels: refactor

#39 chore/#dependabot 적용
  .github/dependabot.yml
Labels: chore

#46 chore/#45 coderabbit 적용
  .coderabbit.yaml
Labels: chore

#48 feature/#47 aop와 인터셉터를 이용한 로깅 구현
  .coderabbit.yaml
  build.gradle
  settings.gradle
  soridam-api/build.gradle
  soridam-api/src/main/java/sorisoop/soridam/api/aspect/ExceptionLoggingAspect.java
  soridam-api/src/main/java/sorisoop/soridam/api/aspect/ServerErrorLoggingAspect.java
  soridam-api/src/main/java/sorisoop/soridam/api/noise/application/NoiseService.java
  soridam-api/src/main/java/sorisoop/soridam/api/user/application/UserService.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/common/AccessExceptionCode.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/common/CustomAccessDeniedException.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/common/CustomAccessDeniedHandler.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/common/UnauthorizedException.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/config/SecurityConfig.java
  soridam-auth/src/main/java/sorisoop/soridam/auth/jwt/JwtAuthenticationEntryPoint.java
  soridam-common/build.gradle
  soridam-common/src/main/java/sorisoop/soridam/common/config/WebConfig.java
  soridam-common/src/main/java/sorisoop/soridam/common/log/annotation/NoLogging.java
  soridam-common/src/main/java/sorisoop/soridam/common/log/interceptor/LoggingInterceptor.java
  soridam-domain/build.gradle
  soridam-domain/src/main/java/sorisoop/soridam/domain/noise/domain/Noise.java
  soridam-domain/src/main/java/sorisoop/soridam/domain/user/domain/User.java
  soridam-global-util/build.gradle
  soridam-global-util/src/main/java/sorisoop/soridam/globalutil/geometry/GeometryUtils.java
  soridam-global-util/src/main/java/sorisoop/soridam/globalutil/logging/HttpReqResUtils.java
  soridam-global-util/src/main/java/sorisoop/soridam/globalutil/logging/LoggingUtils.java
  soridam-global-util/src/main/java/sorisoop/soridam/globalutil/uuid/PrefixedUuid.java
  soridam-global-util/src/main/java/sorisoop/soridam/globalutil/uuid/PrefixedUuidGenerator.java
  soridam-global-util/src/main/java/sorisoop/soridam/globalutil/uuid/UuidPrefix.java
Labels: feature

#51 chore/#50 자동 배포 설정
  .github/workflows/dev-build-deploy.yml
  Dockerfile
Labels: chore
